homework 4
Lubovgroma/Prjctr-course pull request #5
Opened 2023-03-27 10:23 UTC by Lubovgroma

2023-03-28 12:53 UTC, sharkich requested changes

2023-03-28 12:53 UTC, sharkich commented on homework4/task 3.js
> +console.log(movies.sort(byProperty('movieName', '>'))); // виведе масив фільмів посортованих по назві, в алфавітному порядку*
do not use function before declaration

2023-03-28 12:53 UTC, sharkich commented on homework4/task 3.js
> +    }
you can improve the solution is you try to use `a[property]`

2023-03-31 10:21 UTC, Lubovgroma commented on homework4/task1-2.js
> +    return allArg.reduce((a, b)=>a+b);
I have tried to add default values like that --  allArg.reduce((a = 1, b = 1)=>a+b); , but error occurs "Reduce of empty array with no initial value"

2023-03-31 10:23 UTC, Lubovgroma commented on homework4/task 3.js
> +                if ( y[property] > x[property]){
used x[property]

2023-03-31 10:26 UTC, Lubovgroma commented on homework4/task 4.js
> +            clearInterval(timerId);
clearInterval used inside the function

2023-03-31 10:27 UTC, Lubovgroma commented on homework4/task 4.js
> +        return detonatorTimer2(timer-1);
Recursion used

2023-03-31 10:28 UTC, Lubovgroma commented on homework4/task5-6-7.js
> +function someFunction (...arg){
function accepts any amount of arguments

2023-04-03 08:30 UTC, sharkich requested changes

2023-04-03 08:30 UTC, sharkich commented on homework4/task 3.js
> +            return (x,y) => {
Change logic

2023-04-03 08:30 UTC, sharkich commented on homework4/task 4.js
> +            return console.log('BOOM!');
2 lines

2023-04-03 08:30 UTC, sharkich commented on homework4/task 4.js
> +    let timerId = setInterval(() => {
const

2023-04-03 08:30 UTC, sharkich commented on homework4/task 4.js
> +    let timerId = setTimeout(() => {
const

2023-04-03 08:30 UTC, sharkich commented on homework4/task 4.js
> +            return console.log("BOOM!");
2 lines

2023-04-03 08:30 UTC, sharkich commented on homework4/task1-2.js
> +    return allArg.reduce((a, b)=>a+b);
defasult

2023-04-04 09:58 UTC, Lubovgroma commented on homework4/task 4.js
> +            return clearInterval(timerId);
can I return clearInterval(timerId) ?

2023-04-04 09:59 UTC, Lubovgroma commented on homework4/task 4.js
> +            return 1;
added return 1 just to stop recursion, is it ok?

2023-04-04 10:02 UTC, Lubovgroma reviewed
Please check only last updated version: 
[homework 4/last version] (https://github.com/Lubovgroma/Prjctr-course/pull/5/commits/76911b4fa0ad484d88b591da4b96ca6979a2c849)
76911b4

2023-04-08 20:05 UTC, merged